services:
  postgres:
    image: postgres:15-alpine
    container_name: cms_postgres
    environment:
      POSTGRES_DB: cms_db
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migration/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - cms_network

  app:
    build:
      context: .
      args:
        DB_HOST: postgres
        DB_PORT: 5432
        DB_USER: myuser
        DB_PASSWORD: mypassword
        DB_NAME: cms_db
        DB_SSLMODE: disable
        JWT_SECRET: your-super-secret-jwt-key-change-in-production
        PORT: 8080
    container_name: cms_api
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: myuser
      DB_PASSWORD: mypassword
      DB_NAME: cms_db
      DB_SSLMODE: disable
      JWT_SECRET: your-super-secret-jwt-key-change-in-production
      PORT: 8080
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - cms_network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  cms_network:
    driver: bridge